// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkOrder struct {
	ID        int64
	Number    string
	Address   string
	WorkType  string
	Client    string
	Phone     string
	Executor  *string
	Date      pgtype.Date
	Status    string
	Comment   string
	CreatedAt pgtype.Timestamptz
}
