// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Technician struct {
	ID        int64
	FullName  string
	Phone     string
	Active    bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Login        string
	PasswordHash string
	FullName     string
	Role         string
	TechnicianID *int64
	CreatedAt    pgtype.Timestamptz
}

type WorkOrder struct {
	ID           int64
	Number       string
	Address      string
	WorkType     string
	Client       string
	Phone        string
	Date         pgtype.Date
	Status       string
	Comment      string
	CreatedAt    pgtype.Timestamptz
	TechnicianID *int64
}
