// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
insert into work_orders (number, address, work_type, client, phone, executor, date, status, comment)
values ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9)
returning number, address, work_type, client, phone, executor, date, status, comment
`

type CreateOrderParams struct {
	Number   string
	Address  string
	WorkType string
	Client   string
	Phone    string
	Executor *string
	Date     pgtype.Date
	Status   string
	Comment  string
}

type CreateOrderRow struct {
	Number   string
	Address  string
	WorkType string
	Client   string
	Phone    string
	Executor *string
	Date     pgtype.Date
	Status   string
	Comment  string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (*CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Number,
		arg.Address,
		arg.WorkType,
		arg.Client,
		arg.Phone,
		arg.Executor,
		arg.Date,
		arg.Status,
		arg.Comment,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.Number,
		&i.Address,
		&i.WorkType,
		&i.Client,
		&i.Phone,
		&i.Executor,
		&i.Date,
		&i.Status,
		&i.Comment,
	)
	return &i, err
}

const getOrder = `-- name: GetOrder :one
select number, address, work_type, client, phone, executor, date, status, comment
from work_orders
where number = $1
`

type GetOrderRow struct {
	Number   string
	Address  string
	WorkType string
	Client   string
	Phone    string
	Executor *string
	Date     pgtype.Date
	Status   string
	Comment  string
}

func (q *Queries) GetOrder(ctx context.Context, number string) (*GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, number)
	var i GetOrderRow
	err := row.Scan(
		&i.Number,
		&i.Address,
		&i.WorkType,
		&i.Client,
		&i.Phone,
		&i.Executor,
		&i.Date,
		&i.Status,
		&i.Comment,
	)
	return &i, err
}

const listOrders = `-- name: ListOrders :many
select number, address, work_type, client, phone, executor, date, status, comment
from work_orders
order by number desc
`

type ListOrdersRow struct {
	Number   string
	Address  string
	WorkType string
	Client   string
	Phone    string
	Executor *string
	Date     pgtype.Date
	Status   string
	Comment  string
}

func (q *Queries) ListOrders(ctx context.Context) ([]*ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.Number,
			&i.Address,
			&i.WorkType,
			&i.Client,
			&i.Phone,
			&i.Executor,
			&i.Date,
			&i.Status,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderNumber = `-- name: NextOrderNumber :one
select lpad((coalesce(max(number)::int, 0) + 1)::text, 5, '0') as next_number
from work_orders
`

// Следующий номер наряда: max(number)+1 с zero-pad до 5 знаков.
func (q *Queries) NextOrderNumber(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextOrderNumber)
	var next_number string
	err := row.Scan(&next_number)
	return next_number, err
}

const updateOrder = `-- name: UpdateOrder :one
update work_orders
set executor = $1,
    status   = $2
where number = $3
returning number, address, work_type, client, phone, executor, date, status, comment
`

type UpdateOrderParams struct {
	Executor *string
	Status   string
	Number   string
}

type UpdateOrderRow struct {
	Number   string
	Address  string
	WorkType string
	Client   string
	Phone    string
	Executor *string
	Date     pgtype.Date
	Status   string
	Comment  string
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (*UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.Executor, arg.Status, arg.Number)
	var i UpdateOrderRow
	err := row.Scan(
		&i.Number,
		&i.Address,
		&i.WorkType,
		&i.Client,
		&i.Phone,
		&i.Executor,
		&i.Date,
		&i.Status,
		&i.Comment,
	)
	return &i, err
}
