// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
insert into work_orders (number, address, work_type, client, phone, technician_id, date, status, comment)
values ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9)
returning number, address, work_type, client, phone, technician_id, date, status, comment
`

type CreateOrderParams struct {
	Number       string
	Address      string
	WorkType     string
	Client       string
	Phone        string
	TechnicianID *int64
	Date         pgtype.Date
	Status       string
	Comment      string
}

type CreateOrderRow struct {
	Number       string
	Address      string
	WorkType     string
	Client       string
	Phone        string
	TechnicianID *int64
	Date         pgtype.Date
	Status       string
	Comment      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (*CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Number,
		arg.Address,
		arg.WorkType,
		arg.Client,
		arg.Phone,
		arg.TechnicianID,
		arg.Date,
		arg.Status,
		arg.Comment,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.Number,
		&i.Address,
		&i.WorkType,
		&i.Client,
		&i.Phone,
		&i.TechnicianID,
		&i.Date,
		&i.Status,
		&i.Comment,
	)
	return &i, err
}

const getOrder = `-- name: GetOrder :one
select wo.number, wo.address, wo.work_type, wo.client, wo.phone,
       wo.technician_id, t.full_name as executor,
       wo.date, wo.status, wo.comment
from work_orders wo
left join technicians t on t.id = wo.technician_id
where wo.number = $1
`

type GetOrderRow struct {
	Number       string
	Address      string
	WorkType     string
	Client       string
	Phone        string
	TechnicianID *int64
	Executor     *string
	Date         pgtype.Date
	Status       string
	Comment      string
}

func (q *Queries) GetOrder(ctx context.Context, number string) (*GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, number)
	var i GetOrderRow
	err := row.Scan(
		&i.Number,
		&i.Address,
		&i.WorkType,
		&i.Client,
		&i.Phone,
		&i.TechnicianID,
		&i.Executor,
		&i.Date,
		&i.Status,
		&i.Comment,
	)
	return &i, err
}

const listOrders = `-- name: ListOrders :many

select wo.number, wo.address, wo.work_type, wo.client, wo.phone,
       wo.technician_id, t.full_name as executor,
       wo.date, wo.status, wo.comment
from work_orders wo
left join technicians t on t.id = wo.technician_id
order by wo.number desc
`

type ListOrdersRow struct {
	Number       string
	Address      string
	WorkType     string
	Client       string
	Phone        string
	TechnicianID *int64
	Executor     *string
	Date         pgtype.Date
	Status       string
	Comment      string
}

// Наряды. executor — ФИО монтажника через LEFT JOIN (null, если не назначен).
func (q *Queries) ListOrders(ctx context.Context) ([]*ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.Number,
			&i.Address,
			&i.WorkType,
			&i.Client,
			&i.Phone,
			&i.TechnicianID,
			&i.Executor,
			&i.Date,
			&i.Status,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByTechnician = `-- name: ListOrdersByTechnician :many
select wo.number, wo.address, wo.work_type, wo.client, wo.phone,
       wo.technician_id, t.full_name as executor,
       wo.date, wo.status, wo.comment
from work_orders wo
left join technicians t on t.id = wo.technician_id
where wo.technician_id = $1
order by wo.number desc
`

type ListOrdersByTechnicianRow struct {
	Number       string
	Address      string
	WorkType     string
	Client       string
	Phone        string
	TechnicianID *int64
	Executor     *string
	Date         pgtype.Date
	Status       string
	Comment      string
}

// Наряды конкретного монтажника (для роли montazhnik).
func (q *Queries) ListOrdersByTechnician(ctx context.Context, technicianID *int64) ([]*ListOrdersByTechnicianRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByTechnician, technicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListOrdersByTechnicianRow{}
	for rows.Next() {
		var i ListOrdersByTechnicianRow
		if err := rows.Scan(
			&i.Number,
			&i.Address,
			&i.WorkType,
			&i.Client,
			&i.Phone,
			&i.TechnicianID,
			&i.Executor,
			&i.Date,
			&i.Status,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderNumber = `-- name: NextOrderNumber :one
select lpad((coalesce(max(number)::int, 0) + 1)::text, 5, '0') as next_number
from work_orders
`

// Следующий номер наряда: max(number)+1 с zero-pad до 5 знаков.
func (q *Queries) NextOrderNumber(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextOrderNumber)
	var next_number string
	err := row.Scan(&next_number)
	return next_number, err
}

const updateOrder = `-- name: UpdateOrder :one
update work_orders
set technician_id = $1,
    status        = $2
where number = $3
returning number, address, work_type, client, phone, technician_id, date, status, comment
`

type UpdateOrderParams struct {
	TechnicianID *int64
	Status       string
	Number       string
}

type UpdateOrderRow struct {
	Number       string
	Address      string
	WorkType     string
	Client       string
	Phone        string
	TechnicianID *int64
	Date         pgtype.Date
	Status       string
	Comment      string
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (*UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.TechnicianID, arg.Status, arg.Number)
	var i UpdateOrderRow
	err := row.Scan(
		&i.Number,
		&i.Address,
		&i.WorkType,
		&i.Client,
		&i.Phone,
		&i.TechnicianID,
		&i.Date,
		&i.Status,
		&i.Comment,
	)
	return &i, err
}
