// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const loadByTechnician = `-- name: LoadByTechnician :many
select
    t.id,
    t.full_name,
    count(wo.*)                                   as total,
    count(wo.*) filter (where wo.status = 'done')   as done,
    count(wo.*) filter (where wo.status = 'inwork') as inwork
from technicians t
join work_orders wo on wo.technician_id = t.id
    and wo.date between $1::date and $2::date
group by t.id, t.full_name
order by t.full_name
`

type LoadByTechnicianParams struct {
	DateFrom pgtype.Date
	DateTo   pgtype.Date
}

type LoadByTechnicianRow struct {
	ID       int64
	FullName string
	Total    int64
	Done     int64
	Inwork   int64
}

// Загрузка монтажников за период.
func (q *Queries) LoadByTechnician(ctx context.Context, arg LoadByTechnicianParams) ([]*LoadByTechnicianRow, error) {
	rows, err := q.db.Query(ctx, loadByTechnician, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LoadByTechnicianRow{}
	for rows.Next() {
		var i LoadByTechnicianRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Total,
			&i.Done,
			&i.Inwork,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ordersSummaryByPeriod = `-- name: OrdersSummaryByPeriod :one

select
    count(*) filter (where true)                    as total,
    count(*) filter (where status = 'done')         as done,
    count(*) filter (where status = 'inwork')       as inwork,
    count(*) filter (where status = 'cancelled')    as cancelled,
    count(*) filter (where status = 'created')      as created,
    count(*) filter (where status = 'assigned')     as assigned
from work_orders
where date between $1::date and $2::date
`

type OrdersSummaryByPeriodParams struct {
	DateFrom pgtype.Date
	DateTo   pgtype.Date
}

type OrdersSummaryByPeriodRow struct {
	Total     int64
	Done      int64
	Inwork    int64
	Cancelled int64
	Created   int64
	Assigned  int64
}

// Отчёты за период (по дате создания наряда).
// Счётчики по статусам за период. Границы: [date_from, date_to] включительно.
func (q *Queries) OrdersSummaryByPeriod(ctx context.Context, arg OrdersSummaryByPeriodParams) (*OrdersSummaryByPeriodRow, error) {
	row := q.db.QueryRow(ctx, ordersSummaryByPeriod, arg.DateFrom, arg.DateTo)
	var i OrdersSummaryByPeriodRow
	err := row.Scan(
		&i.Total,
		&i.Done,
		&i.Inwork,
		&i.Cancelled,
		&i.Created,
		&i.Assigned,
	)
	return &i, err
}
