// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: technicians.sql

package sqlc

import (
	"context"
)

const countOrdersByTechnician = `-- name: CountOrdersByTechnician :one
select count(*)
from work_orders
where technician_id = $1
`

// Сколько нарядов ссылается на монтажника (для запрета удаления).
func (q *Queries) CountOrdersByTechnician(ctx context.Context, id *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByTechnician, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTechnician = `-- name: CreateTechnician :one
insert into technicians (full_name, phone)
values ($1, $2)
returning id, full_name, phone, active, created_at
`

type CreateTechnicianParams struct {
	FullName string
	Phone    string
}

func (q *Queries) CreateTechnician(ctx context.Context, arg CreateTechnicianParams) (*Technician, error) {
	row := q.db.QueryRow(ctx, createTechnician, arg.FullName, arg.Phone)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteTechnician = `-- name: DeleteTechnician :exec
delete from technicians
where id = $1
`

func (q *Queries) DeleteTechnician(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTechnician, id)
	return err
}

const getTechnician = `-- name: GetTechnician :one
select id, full_name, phone, active, created_at
from technicians
where id = $1
`

func (q *Queries) GetTechnician(ctx context.Context, id int64) (*Technician, error) {
	row := q.db.QueryRow(ctx, getTechnician, id)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
	)
	return &i, err
}

const listActiveTechnicians = `-- name: ListActiveTechnicians :many
select id, full_name, phone, active, created_at
from technicians
where active = true
order by full_name
`

// Только действующие (для селекта назначения).
func (q *Queries) ListActiveTechnicians(ctx context.Context) ([]*Technician, error) {
	rows, err := q.db.Query(ctx, listActiveTechnicians)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Technician{}
	for rows.Next() {
		var i Technician
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTechnicians = `-- name: ListTechnicians :many

select id, full_name, phone, active, created_at
from technicians
order by full_name
`

// CRUD монтажников.
func (q *Queries) ListTechnicians(ctx context.Context) ([]*Technician, error) {
	rows, err := q.db.Query(ctx, listTechnicians)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Technician{}
	for rows.Next() {
		var i Technician
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTechnician = `-- name: UpdateTechnician :one
update technicians
set full_name = coalesce($1, full_name),
    phone     = coalesce($2, phone),
    active    = coalesce($3, active)
where id = $4
returning id, full_name, phone, active, created_at
`

type UpdateTechnicianParams struct {
	FullName *string
	Phone    *string
	Active   *bool
	ID       int64
}

func (q *Queries) UpdateTechnician(ctx context.Context, arg UpdateTechnicianParams) (*Technician, error) {
	row := q.db.QueryRow(ctx, updateTechnician,
		arg.FullName,
		arg.Phone,
		arg.Active,
		arg.ID,
	)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
	)
	return &i, err
}
