// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
select id, login, password_hash, full_name, role, technician_id
from users
where id = $1
`

type GetUserByIDRow struct {
	ID           int64
	Login        string
	PasswordHash string
	FullName     string
	Role         string
	TechnicianID *int64
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.TechnicianID,
	)
	return &i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one

select id, login, password_hash, full_name, role, technician_id
from users
where login = $1
`

type GetUserByLoginRow struct {
	ID           int64
	Login        string
	PasswordHash string
	FullName     string
	Role         string
	TechnicianID *int64
}

// Пользователи (аутентификация).
func (q *Queries) GetUserByLogin(ctx context.Context, login string) (*GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.TechnicianID,
	)
	return &i, err
}
